# Generated by Django 6.0.1 on 2026-02-02 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('plataforma', models.CharField(choices=[('PC', 'PC'), ('Xbox', 'Xbox'), ('PlayStation', 'PlayStation'), ('Switch', 'Switch')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('fecha_lanzamiento', models.DateField()),
            ],
        ),
    ]
