# Generated by Django 6.0.1 on 2026-02-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0003_alter_juego_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='fecha_lanzamiento',
            field=models.DateField(auto_now_add=True),
        ),
    ]
